# 配置檔案版本，請不要更改此數值！
config-version: 1.4.1

# 檢查插件版本是否為最新
check_update:
  enable: true
  notify:
    # 是否於啟動時通知更新
    startup: true
    # 是否於具有 sbp.notify 或 op 權限 的玩家加入時通知更新
    login: true
    # %s 為最新版本號
    message: §bShulkerBoxPreview 已推出 %s, 請在此下載更新:§6https://www.spigotmc.org/resources/shulkerboxpreview.105258

# 自定義插件語言檔，語言檔格式請依照預設配置
lang_lib: https://raw.githubusercontent.com/YTiceice/LangLib/main

# 插件顯示的系統文字
messages:
  command:
    reload: §b已重新讀取所有配置檔案
    no-per: §c你沒有權限使用這個指令

  # 預覽顯示格式
  format:
    # %1s 為物品命名名稱 , %2s 為物品名稱 [例如: 命名石頭 (石頭)]
    display-item: §f%1$s (%2$s)
    # %1s 為物品命名名稱 , %2s 為物品名稱 , %d 為數量 [例如: 命名石頭 (石頭) x64]
    display-items: §f%1$s (%2$s) x%3$d
    # %s 為物品名稱 [例如: 石頭]
    item: §f%s
    # %s 為物品名稱 , %d 為數量 [例如: 石頭 x64]
    items: §f%s x%d

  # 每行顯示幾個物品
  item-per-n-line: 4
  # 每個物品的間隔符
  item-per-n-append: ' , '
  # 每行開頭的字符
  first-per-n-line: '  '

# 背包內的物品是否會受到 “ 切換界伏盒預覽功能 ” 而影響移除/新增預覽
# 倘若開啟，玩家將可以把 “ 沒有預覽 ” 的界伏盒放於商店，可能會導致商店詐欺
# 如果特別有需要防詐欺的話，請將此功能設置為 false
force-update: true

# 是否直接顯示客戶端語言
client-language: true

# 是否自動更新語言檔案
auto-update: true

# 當玩家觸發以下事件時更新預覽資料
enable:
  # 開啟容器
  when-open: true
  # 關閉容器
  when-close: true
  # 撿起物品
  pickup-item: true
  # 切換手上的物品
  held-item: true

# 當開啟或關閉的容器標題為以下之一時更新預覽資料 (可用於避免與選單中的界伏盒衝突)
whitelist:
  open:
    enable: true
    # 預設為原版容器 (倘若關閉，則開啟容器時不更新預覽文字)
    list:
      - Shulker Box
      - Chest
      - Large Chest
      - Brewing Stand
      - Minecart with Hopper
      - Minecart with Chest
      - Item Hopper
      - Ender Chest
      - Dispenser
      - Dropper
      - Furnace
      - Crafting
  # 假設你新增了 "123"，那麼名稱為 123 的界面就會在開啟時更新預覽文字
  close:
    enable: true
    # 預設為原版容器 (倘若關閉，則關閉容器時不更新預覽文字)
    list:
      - Shulker Box
      - Chest
      - Large Chest
      - Brewing Stand
      - Minecart with Hopper
      - Minecart with Chest
      - Item Hopper
      - Ender Chest
      - Dispenser
      - Dropper
      - Furnace
      - Crafting
# 假設你新增了 "123"，那麼名稱為 123 的界面就會在關閉時更新預覽文字

# 是否讓玩家能夠調整是否顯示界伏盒預覽 (/sbppreview)
toggle-command:
  # 若玩家未使用設定指令設定是否啟用預覽，則使用此預設值
  default: true
  # 插件顯示的系統文字
  messages:
    # 使用/sbppreview on後的系統顯示文字
    when-on: §b你已開啟界伏盒預覽功能
    # 使用/sbppreview off後的系統顯示文字
    when-off: §b你已關閉界伏盒預覽功能
    # 當指令輸入者不是玩家的系統顯示文字
    only-player: §c只有玩家能夠使用此指令
    # 當玩家輸入錯指令的的系統顯示文字
    usage: §c用法：/sbppreview <on/off>
