name: ${project.name}
main: tech.ice.plugins.ShulkerBoxPreview.Main
version: ${project.version}
api-version: 1.17
folia-supported: true
author: [ RiceChen_, TangJin ]
commands:
  sbpreload:
    description: 重新讀取所有配置檔案
    usage: /sbpreload
  sbppreview:
    description: 切換是否啟用功能預覽
    usage: /sbppreview <on/off>
    aliases: sbpp
